server:
  port: 8081
spring:
  application:
    name: microservice-one
  zipkin:
    base-url: http://localhost:9410/
eureka:
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://localhost:8181/eureka/