server:
  port: 8081
spring:
  application:
    name: microservice-one
  zipkin:
    baseUrl: http://localhost:9410
    enabled: true
    sender:
      type: web
eureka:
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://localhost:7082/eureka/