server:
  port: 8082
spring:
  application:
    name: microservice-two
  zipkin:
    base-url: http://localhost:9410/
eureka:
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://localhost:7082/eureka/