server:
  port: 9410

spring:
  application:
    name: app-zipkin-service
  datasource:
    schema: classpath:/mysql.sql
    url: jdbc:mysql://localhost:3306/zipkin_service_mysql?autoReconnect=true&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

zipkin:
  storage:
    type: mysql
    mysql:
      host: localhost
      port: 3306
      username: root
      password: root
      db: zipkin_service_mysql


