server:
  port: 9410

spring:
  application:
    name: app-zipkin-server
  datasource:
    schema: classpath:/cassandra3-schema.cql
    url: jdbc:cassandra://127.0.0.1:9042
    contactPoints: localhost
    initialize: true
    continue-on-error: true
  sleuth:
    enabled: true
zipkin:
  storage:
    type: cassandra3